# Generated by Django 6.0.6 on 2026-06-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('remitente', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=500)),
                ('fecha_recibido', models.DateTimeField()),
                ('cuerpo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Correo Procesado',
                'verbose_name_plural': 'Correos Procesados',
                'ordering': ['-fecha_recibido'],
            },
        ),
    ]
