# Generated by Django 6.0.7 on 2026-07-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('retorno', 'Retorno de transferencia'), ('confirmacion', 'Confirmacion de pago'), ('asimilado', 'Asimilado'), ('blindado', 'Blindado'), ('bancarizacion', 'Bancarizacion'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('remitente', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=500)),
                ('fecha_recibido', models.DateTimeField()),
                ('cuerpo', models.TextField(blank=True)),
                ('cuerpo_limpio', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, default='SIN NOMBRE', max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='correos.correoprocesado')),
            ],
            options={
                'verbose_name': 'Correo Procesado',
                'verbose_name_plural': 'Correos Procesados',
                'ordering': ['-fecha_recibido'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='facturas/%Y/%m/%d/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas_pdf/%Y/%m/%d/')),
                ('emisor_nombre', models.CharField(blank=True, max_length=300)),
                ('emisor_rfc', models.CharField(blank=True, max_length=20)),
                ('receptor_nombre', models.CharField(blank=True, max_length=300)),
                ('receptor_rfc', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=25)),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('procesado', 'Procesado'), ('error', 'Error')], default='procesado', max_length=20)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='correos.correoprocesado')),
            ],
            options={
                'verbose_name': 'Factura CFDI',
                'verbose_name_plural': 'Facturas CFDI',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('retorno', 'Retorno de transferencia'), ('confirmacion', 'Confirmacion de pago'), ('asimilado', 'Asimilado'), ('blindado', 'Blindado'), ('bancarizacion', 'Bancarizacion'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d/')),
                ('tipo_archivo', models.CharField(choices=[('pdf_digital', 'PDF Digital'), ('pdf_escaneado', 'PDF Escaneado'), ('imagen', 'Imagen'), ('texto', 'Texto de Correo')], max_length=20)),
                ('estado_ocr', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_extraida', models.DateField(blank=True, null=True)),
                ('banco_extraido', models.CharField(blank=True, max_length=200)),
                ('monto_extraido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cuenta_origen', models.CharField(blank=True, max_length=255)),
                ('cuenta_destino', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('banco_origen', models.CharField(blank=True, max_length=200)),
                ('banco_destino', models.CharField(blank=True, max_length=200)),
                ('empresa_destino', models.CharField(blank=True, max_length=255)),
                ('empresa_correo', models.CharField(blank=True, max_length=255)),
                ('banco_correo', models.CharField(blank=True, max_length=255)),
                ('clabe_correo', models.CharField(blank=True, max_length=255)),
                ('monto_correo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_actualizado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_correo', models.DateField(blank=True, null=True)),
                ('validacion_monto', models.BooleanField(default=False)),
                ('texto_bruto', models.TextField(blank=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('folio_factura_extraido', models.CharField(blank=True, max_length=40, null=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='correos.correoprocesado')),
                ('factura_pagada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos', to='correos.factura')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_depositado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('suma_comisiones_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_retornado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_empresa_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_promotor_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_promotor_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_bancaria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_traslado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_vallux_neta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilidad_vallux', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_pedro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('correo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='correos.correoprocesado')),
            ],
        ),
    ]
