# Generated by Django 6.0.6 on 2026-06-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comprobantes/%Y/%m/%d/')),
                ('tipo_archivo', models.CharField(choices=[('pdf_digital', 'PDF Digital'), ('pdf_escaneado', 'PDF Escaneado'), ('imagen', 'Imagen')], max_length=20)),
                ('estado_ocr', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_extraida', models.DateField(blank=True, null=True)),
                ('banco_extraido', models.CharField(blank=True, max_length=200)),
                ('monto_extraido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('texto_bruto', models.TextField(blank=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='correos.correoprocesado')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-id'],
            },
        ),
    ]
