# Generated by Django 6.0.6 on 2026-06-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0002_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='facturas/%Y/%m/%d/')),
                ('emisor_nombre', models.CharField(blank=True, max_length=300)),
                ('emisor_rfc', models.CharField(blank=True, max_length=20)),
                ('receptor_nombre', models.CharField(blank=True, max_length=300)),
                ('receptor_rfc', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=25)),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('estado', models.CharField(choices=[('procesado', 'Procesado'), ('error', 'Error')], default='procesado', max_length=20)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='correos.correoprocesado')),
            ],
            options={
                'verbose_name': 'Factura CFDI',
                'verbose_name_plural': 'Facturas CFDI',
                'ordering': ['-fecha'],
            },
        ),
    ]
