# Generated by Django 6.0.6 on 2026-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0003_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='cuenta_destino',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='cuenta_origen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
