# Generated by Django 6.0.6 on 2026-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0004_comprobante_cuenta_destino_comprobante_cuenta_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdf/%Y/%m/%d/'),
        ),
    ]
