# Generated by Django 6.0.6 on 2026-06-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0005_comprobante_archivo_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='archivo_pdf',
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdf/%Y/%m/%d/'),
        ),
    ]
