# Generated by Django 6.0.6 on 2026-06-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0006_remove_comprobante_archivo_pdf_factura_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='empresa_correo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha_correo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='monto_correo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='validacion_monto',
            field=models.BooleanField(default=False),
        ),
    ]
