# Generated by Django 6.0.6 on 2026-06-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0007_comprobante_empresa_correo_comprobante_fecha_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='banco_destino',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='banco_origen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='empresa_destino',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
