# Generated by Django 6.0.6 on 2026-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0008_comprobante_banco_destino_comprobante_banco_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='tipo_ingreso',
            field=models.CharField(choices=[('retorno', 'Retorno de transferencia'), ('confirmacion', 'Confirmacion de pago'), ('asimilado', 'Asimilado'), ('blindado', 'Blindado'), ('bancarizacion', 'Bancarizacion'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='correoprocesado',
            name='tipo_ingreso',
            field=models.CharField(choices=[('retorno', 'Retorno de transferencia'), ('confirmacion', 'Confirmacion de pago'), ('asimilado', 'Asimilado'), ('blindado', 'Blindado'), ('bancarizacion', 'Bancarizacion'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
