# Generated by Django 6.0.6 on 2026-06-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0009_comprobante_tipo_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
