# Generated by Django 6.0.6 on 2026-06-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0010_comprobante_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoprocesado',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='correoprocesado',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='correos.correoprocesado'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='tipo_archivo',
            field=models.CharField(choices=[('pdf_digital', 'PDF Digital'), ('pdf_escaneado', 'PDF Escaneado'), ('imagen', 'Imagen'), ('texto', 'Texto de Correo')], max_length=20),
        ),
    ]
