# Generated by Django 6.0.6 on 2026-06-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0011_correoprocesado_message_id_correoprocesado_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='banco_correo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='clabe_correo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='saldo_actualizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='saldo_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
