# Generated by Django 6.0.6 on 2026-06-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0012_comprobante_banco_correo_comprobante_clabe_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_depositado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('suma_comisiones_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_retornado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_empresa_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_promotor_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_promotor_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_bancaria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_traslado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_vallux_neta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilidad_vallux', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_pedro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('correo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='correos.correoprocesado')),
            ],
        ),
    ]
