# Generated by Django 6.0.6 on 2026-06-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0013_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoprocesado',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='SIN NOMBRE', max_length=255, null=True),
        ),
    ]
