# Generated by Django 6.0.6 on 2026-06-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0014_correoprocesado_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
