# Generated by Django 6.0.6 on 2026-06-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0015_factura_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoprocesado',
            name='cuerpo_limpio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
