# Generated by Django 6.0.6 on 2026-06-30 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0016_correoprocesado_cuerpo_limpio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='factura_pagada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos', to='correos.factura'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='folio_factura_extraido',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
