# Generated by Django 6.0.6 on 2026-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0017_comprobante_factura_pagada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='folio_factura_extraido',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
