# Generated by Django 6.0.8 on 2026-08-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Administrador'), ('comercial', 'Comercial'), ('supervisor_reclutamiento', 'Supervisor Reclutamiento'), ('asistente_reclutamiento', 'Asistente Reclutamiento')], default='asistente_reclutamiento', max_length=30),
        ),
    ]
