# Generated by Django 6.0.8 on 2026-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_acceso_comercial_usuario_acceso_cotizador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('usuario_estandar', 'Usuario Estandar')], default='usuario_estandar', max_length=30),
        ),
    ]
