# Generated by Django 6.0.8 on 2026-09-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='acceso_pagos',
        ),
    ]
