# Generated by Django 6.0.8 on 2026-08-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del contacto o prospecto', max_length=200)),
                ('correo', models.EmailField(help_text='Correo donde se enviará la cotización', max_length=254)),
                ('empresa', models.CharField(blank=True, help_text='Nombre de la empresa del cliente', max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='EmpresaEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(help_text='Ej. Sistemas P&M, RecluSystem, etc.', max_length=150)),
                ('host_smtp', models.CharField(default='mail.tudominio.com', help_text='Servidor SMTP de tu Web Hosting', max_length=150)),
                ('puerto_smtp', models.IntegerField(default=465, help_text='Generalmente 465 (SSL) o 587 (TLS)')),
                ('usar_tls', models.BooleanField(default=False)),
                ('usar_ssl', models.BooleanField(default=True)),
                ('correo_remitente', models.EmailField(help_text='Correo corporativo que enviará el mensaje', max_length=254)),
                ('password', models.CharField(help_text='Contraseña del correo', max_length=255)),
            ],
            options={
                'verbose_name': 'Empresa Emisora',
                'verbose_name_plural': 'Empresas Emisoras',
            },
        ),
    ]
