# Generated by Django 6.0.8 on 2026-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correos_cc',
            field=models.CharField(blank=True, help_text='Correos secundarios separados por coma (ej. uno@mail.com, dos@mail.com)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(help_text='Correo principal donde se enviará la cotización', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(default='Sin especificar', help_text='Nombre de la empresa del cliente', max_length=200),
            preserve_default=False,
        ),
    ]
