# Generated by Django 6.0.8 on 2026-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_remove_cliente_nombre_cliente_correos_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaemisora',
            name='asunto_cotizacion',
            field=models.CharField(blank=True, help_text='Asunto personalizado del correo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='cuerpo_cotizacion',
            field=models.TextField(blank=True, help_text='Cuerpo del correo personalizado', null=True),
        ),
    ]
