# Generated by Django 6.0.8 on 2026-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_empresaemisora_asunto_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='calle_numero',
            field=models.CharField(blank=True, help_text='Calle y número', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Municipio / Ciudad', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código Postal', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, help_text='Colonia', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón Social exacta', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(blank=True, default='601 - General de Ley Personas Morales', help_text='Régimen fiscal receptor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, help_text='RFC del cliente receptor', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uso_cfdi_preferido',
            field=models.CharField(blank=True, default='G03 - GASTOS EN GENERAL', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='forma_pago_default',
            field=models.CharField(blank=True, default='03 - TRANSFERENCIA ELECTRÓNICA DE FONDOS', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='metodo_pago_default',
            field=models.CharField(blank=True, default='PUE - Pago en una sola exhibición', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='moneda_default',
            field=models.CharField(blank=True, default='MXN - Peso Mexicano', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='regimen_fiscal',
            field=models.CharField(blank=True, default='601 - General de Ley Personas Morales', help_text='Régimen fiscal del emisor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='rfc',
            field=models.CharField(blank=True, help_text='RFC de la empresa emisora', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='tipo_cambio_default',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='uso_cfdi_default',
            field=models.CharField(blank=True, default='G03 - GASTOS EN GENERAL', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correos_cc',
            field=models.CharField(blank=True, help_text='Correos secundarios separados por coma', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(help_text='Nombre de la empresa / Razón Social', max_length=200),
        ),
        migrations.AlterField(
            model_name='empresaemisora',
            name='nombre_empresa',
            field=models.CharField(help_text='Nombre comercial o razón social de la empresa emisora', max_length=150),
        ),
    ]
