# Generated by Django 6.0.8 on 2026-08-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_cliente_calle_numero_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_unica', models.CharField(blank=True, help_text='Código único como OP-2026-XYZ', max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('datos_formulario', models.JSONField(blank=True, default=dict, help_text='Guarda todas las partidas y configuraciones')),
                ('cotizacion_enviada', models.BooleanField(default=False)),
                ('estado_factura', models.CharField(choices=[('NO_SOLICITADA', 'No Solicitada'), ('ENVIADA_A_MONTERREY', 'Enviada a Monterrey'), ('RECIBIDA_DE_MONTERREY', 'Recibida de Monterrey'), ('ENVIADA_AL_CLIENTE', 'Enviada al Cliente')], default='NO_SOLICITADA', max_length=50)),
                ('xml_factura', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('pdf_factura', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.cliente')),
                ('empresa_emisora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.empresaemisora')),
            ],
            options={
                'verbose_name': 'Operación Comercial',
                'verbose_name_plural': 'Operaciones Comerciales',
            },
        ),
    ]
