# Generated by Django 6.0.8 on 2026-08-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_operacionfacturacion_delete_operacioncomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaemisora',
            name='host_imap',
            field=models.CharField(default='mail.tudominio.com', help_text='Servidor IMAP para leer correos', max_length=150),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='puerto_imap',
            field=models.IntegerField(default=993, help_text='Generalmente 993 (SSL)'),
        ),
    ]
