# Generated by Django 6.0.8 on 2026-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_empresaemisora_host_imap_empresaemisora_puerto_imap'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresas_emisoras',
            field=models.ManyToManyField(blank=True, help_text='Empresas emisoras autorizadas para este cliente', related_name='clientes_relacionados', to='cotizador.empresaemisora'),
        ),
    ]
