# Generated by Django 6.0.8 on 2026-08-27 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_cliente_empresas_emisoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionfacturacion',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, help_text='Cotización original si es una prefactura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefacturas', to='cotizador.operacionfacturacion'),
        ),
        migrations.AddField(
            model_name='operacionfacturacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('COTIZACION', 'Cotización'), ('PREFACTURA', 'Prefactura')], default='COTIZACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='operacionfacturacion',
            name='referencia_unica',
            field=models.CharField(blank=True, help_text='Código único como COT-XYZ o PRE-XYZ', max_length=50, unique=True),
        ),
    ]
