# Generated by Django 6.0.8 on 2026-08-28 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_operacionfacturacion_cotizacion_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionfacturacion',
            name='cotizacion_origen',
        ),
        migrations.AddField(
            model_name='operacionfacturacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que generó la operación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacionfacturacion',
            name='prefactura_origen',
            field=models.ForeignKey(blank=True, help_text='Prefactura original si es una cotización generada desde la bandeja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_hijas', to='cotizador.operacionfacturacion'),
        ),
    ]
