# Generated by Django 6.0.8 on 2026-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0010_remove_operacionfacturacion_cotizacion_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaemisora',
            name='giro_comercial',
            field=models.CharField(blank=True, help_text='Giro o actividad económica de esta empresa emisora (ej. Logística, Construcción)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='notas_estrategia',
            field=models.TextField(blank=True, help_text='Criterios de IA para esta empresa (ej. "Válido repetir conceptos", "Prefiere servicios en 2 fases")', null=True),
        ),
    ]
