# Generated by Django 6.0.8 on 2026-09-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0011_empresaemisora_giro_comercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Texto o descripción del concepto de facturación')),
                ('clave_sat', models.CharField(blank=True, default='80141600', help_text='Clave de producto o servicio del SAT', max_length=20)),
                ('unidad_sat', models.CharField(blank=True, default='E48', help_text='Clave de unidad del SAT (por defecto E48 Unidad de Servicio)', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_autorizados', to='cotizador.cliente')),
                ('empresa_emisora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_cliente', to='cotizador.empresaemisora')),
            ],
            options={
                'verbose_name': 'Concepto por Cliente y Empresa',
                'verbose_name_plural': 'Conceptos por Cliente y Empresa',
            },
        ),
    ]
