# Generated by Django 6.0.8 on 2026-09-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0011_empresaemisora_giro_comercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoEstrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_receptor', models.CharField(blank=True, help_text='Nombre del cliente del histórico (Excel)', max_length=255, null=True)),
                ('clave_sat', models.CharField(default='80141600', help_text='Clave SAT por defecto o importada', max_length=20)),
                ('descripcion', models.TextField(help_text='Texto exacto del concepto facturado históricamente')),
                ('frecuencia', models.IntegerField(default=1, help_text='Número de veces que se ha repetido este concepto en el Excel')),
                ('origen', models.CharField(default='Excel 2026', help_text='Para saber de dónde salió este dato', max_length=50)),
                ('empresa_emisora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_estrategia', to='cotizador.empresaemisora')),
            ],
            options={
                'verbose_name': 'Concepto Histórico',
                'verbose_name_plural': 'Catálogo de Conceptos Históricos',
            },
        ),
    ]
