# Generated by Django 6.0.8 on 2026-09-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0012_conceptocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo principal donde se enviará la cotización', max_length=254, null=True),
        ),
    ]
