# Generated by Django 6.0.7 on 2026-07-23 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Puesto',
                'verbose_name_plural': 'Categorías de Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(help_text="Ej: 'Herramientas / software', 'Competencias blandas'", max_length=150)),
                ('pregunta', models.TextField()),
                ('criterio_evaluacion', models.TextField(help_text='Lo que el entrevistador debe esperar en la respuesta')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='reclutamiento.categoriapreguntas')),
            ],
            options={
                'verbose_name': 'Pregunta de Plantilla',
                'verbose_name_plural': 'Preguntas de Plantillas',
                'ordering': ['categoria', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('nombre_puesto', models.CharField(max_length=200)),
                ('sueldo_ofertado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sueldo_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_republica', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('home_office', 'Home Office')], default='presencial', max_length=20)),
                ('experiencia_minima', models.PositiveIntegerField(help_text='Años de experiencia requeridos')),
                ('escolaridad_requerida', models.CharField(max_length=200)),
                ('herramientas', models.JSONField(blank=True, default=list, help_text='Lista de herramientas requeridas')),
                ('competencias_blandas', models.JSONField(blank=True, default=list)),
                ('factores_exito', models.JSONField(blank=True, default=list)),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria_puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclutamiento.categoriapreguntas')),
                ('consultor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
