# Generated by Django 6.0.7 on 2026-07-23 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('zona_ubicacion', models.CharField(help_text='Ej: Norte de la ciudad, a 30 mins', max_length=200)),
                ('plataforma_origen', models.CharField(blank=True, help_text='Ej: LinkedIn, OCC, Referido', max_length=100, null=True)),
                ('estatus', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_proceso', 'En Proceso'), ('viable', 'Viable'), ('no_viable', 'No Viable'), ('enviado_cliente', 'Enviado al Cliente')], default='nuevo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('consultor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='reclutamiento.vacante')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='EntrevistaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=dict, help_text='Respuestas del filtro inicial')),
                ('resultado', models.CharField(choices=[('viable', 'Viable'), ('no_viable', 'No Viable'), ('observacion', 'En Observación')], max_length=20)),
                ('semaforo', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], max_length=20)),
                ('agenda_entrevista_profunda', models.BooleanField(default=False)),
                ('fecha_agenda', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista_inicial', to='reclutamiento.candidato')),
            ],
            options={
                'verbose_name': 'Entrevista Inicial',
                'verbose_name_plural': 'Entrevistas Iniciales',
            },
        ),
        migrations.CreateModel(
            name='EntrevistaProfunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubros', models.JSONField(default=list, help_text='JSON con rubros evaluados (nivel, puntaje, notas)')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('semaforo', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], max_length=20)),
                ('analisis_ejecutivo', models.TextField(blank=True, null=True)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('brechas', models.TextField(blank=True, null=True)),
                ('resultado_sugerido', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista_profunda', to='reclutamiento.candidato')),
            ],
            options={
                'verbose_name': 'Entrevista Profunda',
                'verbose_name_plural': 'Entrevistas Profundas',
            },
        ),
    ]
