# Generated by Django 6.0.7 on 2026-07-23 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0002_candidato_entrevistainicial_entrevistaprofunda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='vacante',
            name='estado_republica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclutamiento.estado'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='reclutamiento.estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['estado__nombre', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='vacante',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclutamiento.municipio'),
        ),
        migrations.CreateModel(
            name='PropuestaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_puesto', models.TextField()),
                ('entregables_esperados', models.TextField()),
                ('tiempo_estimado_cobertura', models.CharField(help_text='Ej: 2 a 3 semanas', max_length=100)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='propuestas_clientes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vacante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta', to='reclutamiento.vacante')),
            ],
            options={
                'verbose_name': 'Propuesta al Cliente',
                'verbose_name_plural': 'Propuestas al Cliente',
            },
        ),
        migrations.CreateModel(
            name='ReporteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortalezas', models.TextField(help_text='Resumen ejecutivo de fortalezas')),
                ('brechas', models.TextField(help_text='Resumen ejecutivo de brechas/riesgos')),
                ('conclusion', models.TextField(help_text='Conclusión final para el cliente')),
                ('siguiente_paso', models.CharField(max_length=200)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='reportes_candidatos/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_cliente', to='reclutamiento.candidato')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to='reclutamiento.vacante')),
            ],
            options={
                'verbose_name': 'Reporte Cliente',
                'verbose_name_plural': 'Reportes Cliente',
            },
        ),
    ]
