# Generated by Django 6.0.7 on 2026-07-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0003_estado_alter_vacante_estado_republica_municipio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='competencias_blandas',
        ),
        migrations.RemoveField(
            model_name='vacante',
            name='factores_exito',
        ),
        migrations.AddField(
            model_name='categoriapreguntas',
            name='sueldo_promedio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='municipio',
            name='factor_ubicacion',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Multiplicador salarial por zona', max_digits=5),
        ),
        migrations.AddField(
            model_name='vacante',
            name='area_departamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='carrera_especialidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='certificaciones',
            field=models.CharField(blank=True, choices=[('titulo', 'Título'), ('titulo_cedula', 'Título y Cédula'), ('tramite_titulo', 'En trámite Título'), ('tramite_cedula', 'En trámite Cédula')], max_length=50),
        ),
        migrations.AddField(
            model_name='vacante',
            name='competencias_blandas_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='competencias_blandas_sugeridas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='competencias_tecnicas_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='competencias_tecnicas_sugeridas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='contacto_responsable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vacante',
            name='disponibilidad_rolar_turnos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='disponibilidad_viajar',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('no_disponible', 'No disponible'), ('ocasional', 'Disponibilidad ocasional'), ('nacional', 'Disponibilidad nacional'), ('internacional', 'Disponibilidad internacional'), ('total', 'Disponibilidad total')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='vacante',
            name='documentos_necesarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='edad_deseada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacante',
            name='entrevistas_requeridas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='evaluaciones_requeridas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='exclusividad',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='vacante',
            name='experiencia_deseable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='experiencia_no_valida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='factores_exito_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='factores_exito_sugeridos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='fecha_compromiso_terna',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='fecha_ideal_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='funciones_diarias_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='funciones_diarias_sugeridas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='garantia',
            field=models.CharField(blank=True, choices=[('7_dias', '7 días'), ('15_dias', '15 días'), ('30_dias', '30 días'), ('60_dias', '60 días'), ('90_dias', '90 días')], max_length=50),
        ),
        migrations.AddField(
            model_name='vacante',
            name='giro_industria',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='herramientas_proporcionadas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='honorarios_acordados',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='horario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='idioma_requerido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacante',
            name='jefe_directo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='jornada',
            field=models.CharField(choices=[('completa', 'Completa'), ('medio_tiempo', 'Medio Tiempo'), ('fin_semana', 'Fin de Semana')], default='completa', max_length=30),
        ),
        migrations.AddField(
            model_name='vacante',
            name='kpis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='motivo_vacante',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('reemplazo', 'Reemplazo'), ('temporal', 'Temporal')], default='nueva', max_length=20),
        ),
        migrations.AddField(
            model_name='vacante',
            name='nivel_puesto',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('administrativo', 'Administrativo'), ('mando_medio', 'Mando Medio'), ('directivo', 'Directivo')], default='operativo', max_length=30),
        ),
        migrations.AddField(
            model_name='vacante',
            name='numero_candidatos_esperados',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='vacante',
            name='numero_vacantes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vacante',
            name='pagos_adicionales',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='perfiles_no_aceptados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='periodicidad_pago',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal')], default='mensual', max_length=20),
        ),
        migrations.AddField(
            model_name='vacante',
            name='prestaciones',
            field=models.CharField(choices=[('ley', 'Ley'), ('superiores', 'Superiores a las de la ley'), ('honorarios', 'Honorarios'), ('servicios_profesionales', 'Servicios Profesionales')], default='ley', max_length=50),
        ),
        migrations.AddField(
            model_name='vacante',
            name='pretension_salarial_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='puesto_contacto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='quien_decide',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='responsabilidades_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='responsabilidades_sugeridas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vacante',
            name='tiempo_cobertura',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='tipo_contratacion',
            field=models.CharField(choices=[('planta', 'Planta'), ('temporal', 'Temporal'), ('proyecto', 'Proyecto')], default='planta', max_length=30),
        ),
        migrations.AddField(
            model_name='vacante',
            name='urgencia_vacante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacante',
            name='valor_estimado_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vacante',
            name='zonas_no_viables',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='escolaridad_requerida',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='experiencia_minima',
            field=models.PositiveIntegerField(default=0, help_text='Años de experiencia requeridos'),
        ),
    ]
