# Generated by Django 6.0.7 on 2026-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0004_remove_vacante_competencias_blandas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriapreguntas',
            name='giro_industria',
            field=models.CharField(blank=True, help_text='Giro o industria (ej. Industrial, Construcción, TI)', max_length=150, null=True),
        ),
    ]
