# Generated by Django 6.0.7 on 2026-07-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0005_categoriapreguntas_giro_industria'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistaprofunda',
            name='agendar_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrevistaprofunda',
            name='detalles_agenda_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrevistaprofunda',
            name='fecha_entrevista_cliente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrevistaprofunda',
            name='hora_entrevista_cliente',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrevistaprofunda',
            name='modalidad_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
