# Generated by Django 6.0.7 on 2026-08-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0006_entrevistaprofunda_agendar_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaEntrevistaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('rubro', models.CharField(max_length=100)),
                ('pregunta', models.TextField()),
            ],
        ),
    ]
