# Generated by Django 6.0.8 on 2026-08-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0008_vacante_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
