# Generated by Django 6.0.8 on 2026-08-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0010_alter_candidato_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estatus',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_proceso', 'En Proceso'), ('viable', 'Viable'), ('no_viable', 'No Viable'), ('enviado_cliente', 'Enviado al Cliente'), ('seleccionado', 'Seleccionado'), ('cartera', 'En Cartera (No Seleccionado)')], default='nuevo', max_length=20),
        ),
    ]
