# Generated by Django 6.0.8 on 2026-08-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0011_alter_candidato_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='fuente_reclutamiento',
            field=models.CharField(default='No especificada', help_text='Ej: OCC, LinkedIn, Indeed, Referido', max_length=200),
        ),
    ]
