# Generated by Django 6.0.8 on 2026-08-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0012_candidato_fuente_reclutamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='fuente_reclutamiento',
        ),
    ]
